header:
    title: Here you are now
    text: Culture Place
    button: Tell Me More
    buttonlink: "#services" # "#{section}" or "URL/page link"

services:
    title: "Services"
    text: "제라진의 특별한 Services"
    section: services
    list:
      - title: "E-Commerce"
        desc: "온라인 스토어를 통해서 다양한 문화, 예술 관련 굿즈 상품을 판매하고 있습니다. "
        icon: fas fa-shopping-cart #find more at https://fontawesome.com/icons
      - title: "Culturing Book"
        desc: "문화를 담는 책, 컬쳐링북이라는 새로운 개념의 책을 개발하여 문화를 사랑하는 사람들과 함께 책을 채워나가고 있습니다."
        icon: fas fa-book
      - title: "Tyvek"
        desc: "친환경 소재 타이벡을 활용하여 다양한 곳에 소재 공급 및 부가 상품을 개발하고 있습니다."
        icon: fab fa-pagelines
      
     # - title: "[Markdown](https://en.wikipedia.org/wiki/Markdown)"
     #   desc: "Your description here, full **Markdown** support"
     #   icon: fab fa-markdown

portfolio:
    title: "Portfolio"
    text: "Jerajin Project Portfolio."
    section: portfolio
    

timeline:
    title: "About" 
    text: "Jerajin timeline"
    section: timeline
    events:
      - title: "Jerajin Beginnings"
        year: "August 2020"
        desc: "아주대학교 경영대학 창업 지원사업 선정과 함께 스타트업 제라진 설립."
        image: assets/img/timeline/3.jpg
        alt: 
        align: left
      - title: "모비랩 모자이크 지원사업 선정"
        year: "September 2020"
        desc: "주식회사 모비랩에서 주최하는 모자이크 지원 사업에 투자 선정."
        image: assets/img/timeline/time_1.jpeg
        alt: 
        align: right
      - title: "서울시 새활용 공모전 우수상"
        year: "October 2020"
        desc: "타이벡을 활용한 교육용 쿨링컵 키트 제작 아이템을 주제로 우수상(서울특별시장상) 수상."
        image: assets/img/timeline/time_2.jpg
        alt: image alt text
        #align: #default is left       
      - title: "컬쳐링북 펀딩 600% 달성"
        year: "November 2020"
        desc: "텀블벅 역사상 전무후무한 무려 600%라는 엄청난 펀딩 결과 달성."
        image: assets/img/timeline/time_3.jpg
        alt: 
        align: right
    end: "Be Part <br> of Our <br> Story!"

about:
    title: "About Us"
    text: "our story"
    section: about

clients:
    section: clients
    max-height: 100px
    horizontal-scrolling: "" #"yes/no"
    list:
      - title: "AJOU"
        url: https://http://www.ajou.ac.kr/
        logo: assets/img/clients/clie_1.jpg
      - title: "LINC"
        url: https://https://linc.ajou.ac.kr/
        logo: assets/img/clients/clie_2.jpg
      - title: "서울시"
        url: https://http://www.seoulup.or.kr/
        logo: assets/img/clients/clie_3.jpg
      - title: "모비랩"
        url: https://www.facebook.com/mobizlab/
        logo: assets/img/clients/clie_4.jpg
    
team:
    title: "OUR AMAZING TEAM"
    text: "어벤저스 Jerajin 팀원을 소개합니다"
    subtext: 능력있는 당신을 기다리고 있습니다..!
    section: team
    people:
      - name: "허정민"
        role: "CEO"
        image: assets/img/team/team_1.jpg
        social:
          - url: https://instagram.com/j25ngmini
            icon: fab fa-instagram
          - url: https://facebook.com/zestjm
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "최준규"
        role: "Brand Marketer"
        image: assets/img/team/team_2.jpg
        social:
          - url: https://instagram.com/chchq_
            icon: fab fa-instagram
          - url: https://facebook.com/profile.php?id=100004883802796
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "신석철"
        role: "Product Manager"
        image: assets/img/team/team_3.jpg
        social:
          - url: https://instagram.com/such_sh
            icon: fab fa-instagram
          - url: https://facebook.com/profile.php?id=100005184764074
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "김세희"
        role: "Product Manager"
        image: assets/img/team/team_4.jpg
        social:
          - url: https://instagram.com/s2_hee_k
            icon: fab fa-instagram
          - url: https://facebook.com/profile.php?id=100007195958444
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "전다예"
        role: "Sales Manager"
        image: assets/img/team/team_5.jpg
        social:
          - url: https://instagram.com/lmallyes
            icon: fab fa-instagram
          - url: https://facebook.com/daye1224
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "허진아"
        role: "Sales Manager"
        image: assets/img/team/team_6.jpg
        social:
          - url: https://instagram.com/lucid_xx1
            icon: fab fa-instagram
          - url: https://facebook.com/wlsdkgj520
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "마진경"
        role: "Designer"
        image: assets/img/team/team_7.jpg
        social:
          - url: https://instagram.com/moonscape1234
            icon: fab fa-instagram
          - url: https://facebook.com/profile.php?id=100026211195776
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in

contact:
    title: "Contact Us"
    text: "문의사항은 아래 남겨주시면 빠르게 회신드리겠습니다."
    section: contact
    
footer:
    legal: "Privacy Policy"
    social:
      - url: https://twitter.com
        icon: "fab fa-twitter"  
      - url: https://facebook.com
        icon: "fab fa-facebook-f"
      - url: https://linkedin.com
        icon: "fab fa-linkedin-in"
      - url: https://github.com/raviriley/agency-jekyll-theme
        icon: "fab fa-github"
      - url: https://instagram.com/culturingbook/
        icon: "fab fa-instagram"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
